# Generated by Django 4.2 on 2023-04-09 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('auto_concern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutomobilkinAPIApp.autoconcern')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start_release', models.IntegerField()),
                ('year_finish_release', models.IntegerField()),
                ('generation', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('model_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutomobilkinAPIApp.modelcar')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField()),
                ('body_type', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('LIFTBACK', 'Лифтбек'), ('SUV', 'Внедорожник')], max_length=9)),
                ('transmission_type', models.CharField(choices=[('AUTOMATIC', 'Автоматическая'), ('ROBOTIC', 'Роботизированная'), ('MECHANIC', 'Механическая'), ('VARIATOR', 'Вариатор')], max_length=9)),
                ('engine_type', models.CharField(choices=[('GASOLINE', 'Бензиновый'), ('DISEL', 'Дизельный'), ('HYBRID', 'Гибридный'), ('ELECTIRC', 'Электрический')], max_length=8)),
                ('engine_volume', models.FloatField()),
                ('engine_power', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('drive_type', models.CharField(choices=[('REAR', 'Задний'), ('FRONT', 'Передний'), ('FULL', 'Полный')], max_length=5)),
                ('year_of_release', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('price_rubles', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('count_owners', models.IntegerField()),
                ('steering_wheel_type', models.CharField(choices=[('LEFT', 'Левый'), ('RIGHT', 'Правый')], max_length=5)),
                ('vin_code', models.CharField(max_length=17)),
                ('state_number', models.CharField(max_length=9)),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('model_car_generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutomobilkinAPIApp.modelcargeneration')),
            ],
        ),
    ]
